---
# tasks file for Nexus
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install wget
  yum:
    name: wget
    state: present

- name: install java-1.8.0-openjdk
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present

- name: Creates directory
  file:
    path: /app
    state: directory

- name: download nexus
  get_url:
    url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /app

- name: Extract nexus into /app
  unarchive:
    src: /app/nexus-3.22.0-02-unix.tar.gz 
    dest: /app
    remote_src: yes

- name: rename folder
  copy:
    src: /app/nexus-3.22.0-02
    dest: /app/nexus
    remote_src: yes

- name: Add the nexus
  user:
    name: nexus


- name: Change file ownership, of nexus
  file:
    path: /app/nexus
    owner: nexus

- name: Change file ownership, of sonatype-work
  file:
    path: /app/sonatype-work
    owner: nexus


- name: Uncomment run_as_user parameter and set run_as_user="nexus"
  lineinfile:
    path: /app/nexus/nexus-3.22.0-02/bin/nexus.rc
    regexp: '^# run_as_user'
    line: 'run_as_user="nexus"'

- name: Ansible create file if it doesn't exist nexus.service
  file:
    path: "/etc/systemd/system/nexus.service"
    state: touch

- name: add block to nexus.service
  blockinfile:
    path: /etc/systemd/system/nexus.service
    block: |
      [Unit]
      Description=nexus service
      After=network.target
      
      [Service]
      Type=forking
      LimitNOFILE=65536
      User=nexus
      Group=nexus
      ExecStart=/app/nexus/bin/nexus start
      ExecStop=/app/nexus/bin/nexus stop
      User=nexus
      Restart=on-abort
      
      [Install]
      WantedBy=multi-user.target


- name: chkconfig nexus on
  command: chkconfig nexus on

- name: start nexus
  service:
    name: nexus
    state: started





    





